GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Call Dad"
}

###

DELETE http://localhost:3001/todo/delete/659c722fb8936d0843cda967

###

PUT http://localhost:3001/todo/complete/6599e21f46a864d4004ee471